/* eo-fix.js — إصلاح EasyOrders: جلسة مضمونة + أزرار بتكلّمك + فحص مرئي */
window.eoEnsureSession=async function(){try{if(eoSessionReady&&localStorage.getItem(EO_TOKEN_KEY))return true}catch(e){}try{eoSetResult('loading','⏳ [1/2] تجهيز جلسة آمنة…')}catch(e){}try{var r=await fetch('/api/easyorders/auth/ensure',{method:'POST',headers:{'Content-Type':'application/json'}});if(!r.ok){try{eoSetResult('err','✕ [1/2] السيرفر ردّ '+r.status+' — حدّث الصفحة')}catch(e){}return false}var j=await r.json();if(j&&j.token){localStorage.setItem(EO_TOKEN_KEY,j.token);try{eoSessionReady=true}catch(e){}return true}try{eoSetResult('err','✕ [1/2] مفيش جلسة: '+(j&&j.error?j.error:'استجابة غير متوقعة'))}catch(e){}}catch(e){try{eoSetResult('err','✕ [1/2] تعذّر الوصول: '+e.message)}catch(x){}}return false};
window.eoReady=window.eoEnsureSession;
window.eoApi=async function(path,body,method){var tk=localStorage.getItem(EO_TOKEN_KEY)||'';var o={headers:{'Content-Type':'application/json','x-marketer-token':tk}};if(body!==undefined){o.method=method||'POST';o.body=JSON.stringify(body)}else if(method){o.method=method}var r=await fetch('/api/easyorders'+path,o);if(r.status===401){try{eoSessionReady=false}catch(e){}localStorage.removeItem(EO_TOKEN_KEY);throw new Error('انتهت الجلسة — دوس الزرار تاني')}var j=await r.json().catch(function(){return{}});if(!r.ok)throw new Error(j.error||('خطأ '+r.status));return j};
window.eoTest=async function(){var b=eo$('eoTestBtn');if(b){b.disabled=true;b.textContent='⏳ جارٍ…'}eoSetResult('loading','⏳ [1/3] تجهيز الجلسة…');if(!(await eoEnsureSession())){if(b){b.disabled=false;b.textContent='🔌 اختبار الاتصال'}return}var k=eo$('eoApiKey').value.trim();if(!k){eoSetResult('err','الصق مفتاح الـ API أولاً');if(b){b.disabled=false;b.textContent='🔌 اختبار الاتصال'}return}eoSetResult('loading','⏳ [2/3] اختبار المفتاح على EasyOrders…');try{var r=await eoApi('/connection/test',{apiKey:k});eoSetResult(r.ok?'ok':'err',r.ok?'✓ الاتصال ناجح — المفتاح صالح':('✕ '+(r.error||'فشل الاتصال')))}catch(e){eoSetResult('err','✕ [2/3] '+e.message)}finally{if(b){b.disabled=false;b.textContent='🔌 اختبار الاتصال'}}};
window.eoSave=async function(){var b=eo$('eoSaveBtn');if(b){b.disabled=true;b.textContent='⏳ جارٍ…'}eoSetResult('loading','⏳ [1/3] تجهيز الجلسة…');if(!(await eoEnsureSession())){if(b){b.disabled=false;b.textContent='💾 حفظ وربط المتجر'}return}var k=eo$('eoApiKey').value.trim(),s=eo$('eoStoreId').value.trim();if(!k){eoSetResult('err','مفتاح الـ API مطلوب');if(b){b.disabled=false;b.textContent='💾 حفظ وربط المتجر'}return}eoSetResult('loading','⏳ [2/3] التحقق وتشفير المفتاح وحفظه…');try{var r=await eoApi('/connection',{apiKey:k,storeId:s});eoSetResult('ok','✅ [3/3] تم الربط بنجاح'+(r.store_name?' — '+r.store_name:''));eoToast('تم ربط المتجر ✓');eo$('eoApiKey').value='';if(typeof eoLoadAll==='function')eoLoadAll()}catch(e){eoSetResult('err','✕ [2/3] '+e.message)}finally{if(b){b.disabled=false;b.textContent='💾 حفظ وربط المتجر'}}};
window.eoDiag=async function(){var L=['🩺 <b>تقرير الفحص</b>'];eoSetResult('loading',L.join('<br>'));var tk=localStorage.getItem(EO_TOKEN_KEY);L.push('• token مخزّن: '+(tk?'نعم':'لا'));eoSetResult('loading',L.join('<br>'));try{var r1=await fetch('/api/easyorders/auth/ensure',{method:'POST',headers:{'Content-Type':'application/json'}});var j1=await r1.json().catch(function(){return{}});L.push('• /auth/ensure → HTTP '+r1.status+(j1&&j1.token?' ✓':' ✕ '+(j1&&j1.error?j1.error:'')));eoSetResult('loading',L.join('<br>'));var u=(j1&&j1.token)||tk;if(u){var r2=await fetch('/api/easyorders/auth/me',{headers:{'x-marketer-token':u}});L.push('• /auth/me → HTTP '+r2.status+(r2.ok?' ✓ جلسة صالحة':' ✕ مرفوضة'))}else L.push('• /auth/me → تخطي')}catch(e){L.push('• خطأ شبكة: '+e.message)}eoSetResult('ok',L.join('<br>'))};
window.eoInjDiag=function(){var s=eo$('eoSaveBtn');if(s&&!eo$('eoDiagBtn')){var b=document.createElement('button');b.className='eo-btn-ghost';b.id='eoDiagBtn';b.textContent='🩺 فحص';b.onclick=window.eoDiag;s.parentNode.insertBefore(b,s.nextSibling)}};
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',window.eoInjDiag)}else{window.eoInjDiag()}
/* go-override-removed-v23 */
