window.THEME={id:'premium',name:'Premium',gridClass:'products-grid',titleClass:'section-title',wrapClass:'container section',hideToolbar:true,cssUrl:'/themes/premium.css',
header:()=>`<header class="store-header"><div class="container header-inner"><div class="logo">🛍️ <span>${STORE.name||'Rab7na'}</span></div><nav class="main-nav"><a class="active">الرئيسية</a><a onclick="document.querySelector('.products-grid').scrollIntoView({behavior:'smooth'})">المنتجات</a></nav><div class="search-box"><input placeholder="ابحث عن منتج..." oninput="doSearch(this.value)"></div><button class="icon-btn cartb" onclick="openCart()">🛒<i id="cc">0</i></button></div></header>`,
hero:()=>`<div class="container"><div class="hero fade-up"><div class="hero-content"><h1>${STORE.hero||'تسوّق أحدث المنتجات بأفضل الأسعار'}</h1><p>${STORE.sub||'شحن سريع • الدفع عند الاستلام • إرجاع مجاني'}</p><button class="btn btn-primary" onclick="document.querySelector('.products-grid').scrollIntoView({behavior:'smooth'})">تسوّق الآن ❯</button></div></div></div>`,
categories:()=>`<div class="container"><div class="categories">${getCats().slice(1).map(function(c){return '<div class="category" onclick="setCat(\''+c+'\')"><span style="font-size:26px">🛍️</span><span>'+c+'</span></div>'}).join('')}</div></div>`,
card:(p,i)=>{var old=Math.round(p.price*1.25),off=Math.round(100-(p.price/old*100));return `<div class="product-card fade-up"><span class="product-badge">-${off}%</span><button class="favorite-btn">♡</button><div class="product-image"><img src="${p.image||''}" loading="lazy" onclick="openP(${i})"></div><div class="product-info"><div class="product-title">${p.name}</div><div class="product-rating">★★★★★</div><div class="product-price"><span class="price">${fmt(p.price)}</span><span class="old-price">${fmt(old)}</span></div><div class="product-actions"><button class="add-cart" onclick="openP(${i})">🛒 أضف للسلة</button><button class="quick-view" onclick="openP(${i})">👁</button></div></div></div>`},
sections:['hero','categories','featured','banner','products'],
banner:()=>`<div class="container"><div class="promo-banner"><h2>🔥 عروض حصرية لفترة محدودة</h2><p>خصومات تصل حتى 40% على منتجات مختارة — لا تفوّت الفرصة</p></div></div>`,
footer:()=>`<footer class="store-footer"><div class="container footer-grid"><div><h3>🛍️ ${STORE.name||'Rab7na'}</h3><p>${STORE.sub||'متجر إلكتروني موثوق'}</p></div><div><h3>روابط</h3><a>الرئيسية</a><a>المنتجات</a><a>العروض</a></div><div><h3>الدعم</h3><a>تواصل معنا</a><a>سياسة الإرجاع</a></div><div><h3>الدفع</h3><p>💵 الدفع عند الاستلام</p></div></div></footer>`,
mobileNav:()=>`<nav class="mobile-bottom-nav"><a class="active"><span class="icon">🏠</span>الرئيسية</a><a><span class="icon">🛍️</span>المنتجات</a><a onclick="openCart()"><span class="icon">🛒</span>السلة</a></nav>`};
